default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['SUPABASE_HOST'] %>
  username: <%= ENV['SUPABASE_USERNAME'] %>
  password: <%= ENV['SUPABASE_PASSWORD'] %>
  sslmode: require

development:
  primary:
    <<: *default
    database: <%= ENV['SUPABASE_DATABASE'] || 'postgres' %>
  cache:
    <<: *default
    database: <%= ENV['SUPABASE_DATABASE'] || 'postgres' %>
  queue:
    <<: *default
    database: <%= ENV['SUPABASE_DATABASE'] || 'postgres' %>
  cable:
    <<: *default
    database: <%= ENV['SUPABASE_DATABASE'] || 'postgres' %>

test:
  primary:
    <<: *default
    database: <%= ENV['SUPABASE_DATABASE'] || 'postgres' %>
  cache:
    <<: *default
    database: <%= ENV['SUPABASE_DATABASE'] || 'postgres' %>
  queue:
    <<: *default
    database: <%= ENV['SUPABASE_DATABASE'] || 'postgres' %>
  cable:
    <<: *default
    database: <%= ENV['SUPABASE_DATABASE'] || 'postgres' %>

production:
  primary:
    <<: *default
    database: <%= ENV['SUPABASE_DATABASE'] || 'postgres' %>
  cache:
    <<: *default
    database: <%= ENV['SUPABASE_DATABASE'] || 'postgres' %>
  queue:
    <<: *default
    database: <%= ENV['SUPABASE_DATABASE'] || 'postgres' %>
  cable:
    <<: *default
    database: <%= ENV['SUPABASE_DATABASE'] || 'postgres' %>
