default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['SUPABASE_HOST'] %>
  username: <%= ENV['SUPABASE_USERNAME'] %>
  password: <%= ENV['SUPABASE_PASSWORD'] %>
  sslmode: require

development:
  <<: *default
  database: <%= ENV['SUPABASE_DATABASE'] || 'postgres' %>

test:
  <<: *default
  database: <%= ENV['SUPABASE_DATABASE'] || 'postgres' %>

production:
  <<: *default
  database: <%= ENV['SUPABASE_DATABASE'] || 'postgres' %>

# Add this section to fix the cable database issue
cable:
  <<: *production
